### ISSUE TITLE
Snek in the Pipeline

### ISSUE THREAD

**Issue by kleberbaum** [snek-at/sitp#1]
**User Stories**
- As a company I want to be able to get an in depth source code analyzes, to be able to monitor the work of my employees.

**Is your feature request related to a problem? Please describe.**
Snek in the Pipeline should be a plugin for CI/CD pipelines to enable in depth source code analyzes.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/55298934/88191342-a1ecaa00-cc3b-11ea-8877-1bbe32f799bd.png)

***Engine - EC - OPS - SITP Workflow Overview***

![image](https://user-images.githubusercontent.com/52858351/88515682-601d8400-cfec-11ea-8a12-4420f78387d7.png)

Solutions that can be implemented:
- Pipeline analyzer
- GQL Client for:
  + OPS (https://github.com/snek-at/ops)

**Requirements**
- [x] Snek in the Pipeline Concept. #2
- [x] Template Repository for Go. #3 
- [x] Local GitLab Server for Pipeline. #4 
- [x] Pipeline Knowledge. #5 
- [x] Update the coding Guideline for Go. https://github.com/snek-at/tonic/issues/7  

**Milestones**
<table>
   <tbody>
      <tr>
         <th align="left" width=200px><b>Feature Milestones</b></th>
         <th align="left" width=250px>Completed at in RFC 2822 format</th>
      </tr>
      <tr>
         <td>Feature Designed</td>
         <td>Thu, 23 Jul 2020 16:38:31 +0200</td>
      </tr>
      <tr>
         <td>Requirements Fulfilled</td>
         <td>Mon, 27 Jul 2020 14:02:18 +0200</td>
      </tr>
      <tr>
         <td>Feature Reviewed</td>
         <td>Mon, 27 Jul 2020 14:06:18 +0200</td>
      </tr>
      <tr>
         <th align="left"><b>Opportunity Milestones</b></th>
         <th align="left">Completed at in RFC 2822 format</th>
      </tr>
      <tr>
         <td>Implementation Done</td>
         <td>Tue, 13 Aug 2020 16:25:00 +0200</td>
      </tr>
      <tr>
         <td>Implementation Reviewed</td>
         <td></td>
      </tr>
      <tr>
         <td>Implementation Deployed</td>
         <td></td>
      </tr>
   </tbody>
</table>
